### ISSUE TITLE
Error in nlsModel

### ISSUE THREAD

**Issue by GeoTuxMan** [cbahlai/monarch_regime#6]
[Sprat_Catch.zip](https://github.com/cbahlai/monarch_regime/files/2940495/Sprat_Catch.zip)

Hi,

I have a dataset with catch values from Sprat, and I want to detect the major changes(large, abrupt, persistent) in my dataset.
But, I have some errors:
> nbreaker(test1)
Error in nlsModel(formula, mf, start, wts) : 
  singular gradient matrix at initial parameter estimates
> AICtally(test1)
Error in nlsModel(formula, mf, start, wts) : 
  singular gradient matrix at initial parameter estimates
> allfits(test1)
Error in nlsModel(formula, mf, start, wts) : 
  singular gradient matrix at initial parameter estimates

I look forward for some tips.

All the best !
George

**Comment by cbahlai** [comment]
Hi George-

I apologize, the notification for this got buried. I created a little R script to run your data through and it seems to work on my system- check it out here: https://github.com/cbahlai/monarch_regime/blob/master/tests/forGeorge.R
Give it a try and let's see if you still get the error, and if we can triangulate when it's happening!

Best,
-Christie

**Comment by GeoTuxMan** [comment]
Hi Christie,

Thank you very much for the script...now work fine...
But, if I want to see more visual results(i.e. plots) , it's need to add
new lines in script ? or to modify the existing lines ?

All the best !
George


În lun., 25 mar. 2019 la 20:13, Christie Bahlai <notifications@github.com>
a scris:

**Comment by cbahlai** [comment]
Great! Glad it was an easy fix. Interesting results- it looks like there were different patterns in the two response variables that you were measuring- do let me know what you find- and if the breaks coming out make sense relative to environmental variables!

I didn't build custom plotting modules for this particular product but the plots I used in the manuscript should be fairly easy to duplicate- here's the script for the monarch example:

https://github.com/cbahlai/monarch_regime/blob/master/plot_monarch_figures.R
